### PR TITLE
HW with gradle

### PR DESCRIPTION
**Pull request by Vladyslove**
Creating test. 
Notice: without task 'execute' and method 'main'

### CODE REVIEW

**Comment by Dmitry404** [comment]
This is barely the repo you wanted to fork :) Fork this one please https://github.com/jelementary-sparrows/homework-with-gradle

**Comment by Vladyslove** [comment]
Thank you for feedback, but, what did i wrong? I forked "this one" repository : "https://github.com/jelekmentary-sparrows/homework-with-gradle", made clone, made HW with gradle, manipulated with tests for ArraysCopier & BitwiceCalc,  pushed, made pull request - all as I did earlier with homework repository and as you said in the end of lesson10.

**Comment by Dmitry404** [comment]
No worries. All if fine but wrong repository which you created PR to. Look at the URL in the address bar. It's not the repo you cloned, right?

**Comment by Vladyslove** [comment]
I'm confused and not quite understood what did i wrong :). I will try to come on today's lesson earlier and ask you again. Maybe tet-a-tea I will understand and resolve my problem.

**Comment by Dmitry404** [comment]
You created a Pull Request to this repo, which URL is https://github.com/Dmitry404/homework-with-gradle. When the correct URL was https://github.com/jelementary-sparrows/homework-with-gradle

**Pull request closed without merging**
